#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

pnpm dlx nx affected:lint --fix --parallel
pnpm dlx nx affected:build --parallel
